Button tokens updates
publy-korea/design-tokens pull request #6
Opened 2023-06-28 09:59 UTC by minhyokim

2023-06-29 09:48 UTC, kimjson requested changes
코멘트 확인 부탁드립니다

2023-06-29 09:48 UTC, kimjson commented on tokens.json
> +              "inabled": {
@minhyokim 오타가 있네요 enabled?

2023-06-29 09:48 UTC, kimjson commented on tokens.json
> +                "value": "{color.slate.100}",
공백이 왜 추가되었을까요... 혹시 json 을 직접 수정하셨나요?

2023-07-06 01:15 UTC, minhyokim commented on tokens.json
> +                "value": "{color.slate.100}",
오 아니요 그렇진 않습니다만... 뭔가 삭제하거나 했을 때 생기는걸까요

2023-07-06 01:15 UTC, minhyokim commented on tokens.json
> +              "inabled": {
수정하겠슴다

2023-07-10 06:58 UTC, kimjson commented on tokens.json
> +                "value": "{color.slate.100}",
아하 그렇다면 상관 없을 거 같아요

2023-07-10 06:58 UTC, kimjson commented on tokens.json
> +              "inabled": {
@minhyokim 요거 아직 수정 안 된 거 같아요. 그리고 다른 곳도 inabled 라고 오타 되어 있는 곳 있어서 같이 확인해주시면 감사하겠습니다.

2023-07-10 09:41 UTC, kimjson approved these changes

2023-07-10 09:41 UTC, merged